### ISSUE TITLE
代码请教

### ISSUE THREAD

**Issue by mumukehao** [HaitaoMao/Node-Classification-Analysis#1]
你好！读了您的Demystify-structural-disparity这篇文章，觉得受益匪浅。因此想重跑观测您的结果。但是，您提供的代码可能是早期的版本，会有一些bug，并且readme中Analsysis experiment部分您的代码中没有体现。请问可以提供完整的代码版本吗？如果可以，不胜感激！
非常期待您的回复！
附：代码疑似有疏漏的部分（之一）：（也可能是我代码理解错了？但是按照我的思路修改就可以正常运行了）：        
if 'Cora' in args.dataset:
 xdata.edge_index = data.edge_index.to(torch.int64)
 xdata.train_mask = data.train_masks[seed]  
 xdata.val_mask = data.val_masks[seed]
 xdata.test_mask = data.test_masks[seed]，将[seed]去掉就可以正常运行了）

**Comment by HaitaoMao** [comment]
你好，你用的mask是默认的mask 20 per class, 500, 1000 可以按着paper里的实验setting去下载一个 20 per class, 30 per class, all else 的mask。这个mask有10个，测出来的效果会更robust一些。 分析的实验（尤其是各种画图）代码比较脏，pipeline还没有整理。如果您有需要的话我可以尽快更新下您需要的那组实验

**Comment by mumukehao** [comment]
非常感谢您的回复！分析实验的图，最感兴趣的是performance comprasion between GCN and deeper GNNs，其次performance between GCN and MLP-based models（两个代码应该相差不大）（感觉这两点分析不同GNN在何处起作用分析的特别棒）。如果您可以更新这组实验，不胜感激！
其次，idd应该没有用到吧，这个也报错，注掉后，这处才可以运行。并且argparse中也没有idd

**Comment by WadeAech** [comment]
> 你好，你用的mask是默认的mask 20 per class, 500, 1000 可以按着paper里的实验setting去下载一个 20 per class, 30 per class, all else 的mask。这个mask有10个，测出来的效果会更robust一些。 分析的实验（尤其是各种画图）代码比较脏，pipeline还没有整理。如果您有需要的话我可以尽快更新下您需要的那组实验

作者你好，您的文章非常的有见地👍
但是在复现时我也遇到了楼主的问题，其中貌似缺失了很多文件，请问您能提供完整的代码和文件吗 我将非常感激

**Comment by HaitaoMao** [comment]
Updating now
